language: java
sudo: false
dist: trusty
jdk: oraclejdk8
install: true
script:
- npm install -g polymer-cli
- npm install -g bower
- "./gradlew -version"
- "./gradlew build"
- "./gradlew archiveZip"
notifications:
  email: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: iNs+TwU63s8FwNhOx/rTpAFKAb6duCLAM95FGjB29Oyvs503CpBUUQnw7VjwQjYhhqHfLt2i7djwweEKL7DUaRhmX5bZyCJj9WCCQRINtgNOD/AkpFQ8VHRwRgbEwUb0LCxVe1YhT+U7fd7PuPNMJnWvo/NfGt4h7xOnRJzCH+jygcrf7oR/BcmNPFD+G1Q7lDZeE4m4WVBUuuUzxAKx3Nceb7x/eC/AhSNBqdQrFHTrgWq45fG7XwzIH4uKDWDjGFdPid0VAIFR0oFgseuwv/+GG30uqE8Vdg3hXfLMX++cokjE0jGl5HL1+LKKIf7YKZAE61p0W7NAjjd/4Bp8MmFHymjneAvpXP+fQRoZwYI4GupLzEZoCFFVXGR/mjTm36jaZEAJVmm5u1Go49kfdvYhnyLQj5CsjRkzX2fp0dK/t3kZeuwxQXHPmcR9eebkIc+/KGCWlyVVp7J60wyxAm9e1wizQPPUg7hBJk6jrb32fnoOQHRBPxQUBJKI1CdTvXs2O5BEggRJH9KFeN3fI3pbR7I1TjelhTlu+XAyEmwwWVKW5Km6YfeNHLkQdZpJ80xLJz9+qD8fKD5xrnJhTDHTcs0GkPqqe8jNgBEMkb+3vdPymqxF16XpNYHfbX/uzqDPEqYRlcVQ8yu5/c8dowFvtO02VcvBgeip5vuVuPk=
  file_glob: true
  file:
    - build/distributions/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
env:
  global:
  - GRADLE_OPTS="-Xms256m"
  - JDK_JAVA_OPTIONS='--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED
    --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/sun.net.dns=ALL-UNNAMED
    --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED
    --add-opens=java.base/sun.nio.ch=ALL-UNNAMED'
